import:
- ~/.config/alacritty/rose-pine-moon.yml

env:
  TERM: xterm-256color

shell:
  program: /bin/zsh
  args:
    - -l
  #   - -c
  #   - "source ~/.zshrc; tmux attach 2> /dev/null || tmux"

window:
  decorations: none
  startup_mode: Maximized
  dynamic_padding: true
  option_as_alt: Both

dynamic_title: true

font:
  normal:
    family: VictorMono Nerd Font
    style: Regular
  bold:
    style: SemiBold
  italic:
    style: Italic
  bold_italic:
    style: SemiBold Italic
  size: 21.25
  AppleFontSmoothing: true

cursor:
  style:
    shape: Underline

mouse:
  hide_when_typing: true

live_config_reload: true

key_bindings:
  - { key: Paste,                  action: Paste }
  - { key: Return, mods: Command,  action: ToggleFullScreen }

  # tmux bindings
  # open and close panes
  - { key: D, mods: Command,       chars: "\x02\x25" }    # horizontal split
  - { key: D, mods: Command|Shift, chars: "\x02\x22" }    # vertical split
  - { key: W, mods: Command,       chars: "\x02\x78" }    # close pane
  - { key: M, mods: Command,       chars: "\x02\x21" }    # turn split into new window
  # move between panes
  - { key: H, mods: Command, chars: "\x02\x1b\x5b\x44" }  # move focus left
  - { key: J, mods: Command, chars: "\x02\x1b\x5b\x42" }  # move focus right
  - { key: K, mods: Command, chars: "\x02\x1b\x5b\x41" }  # move focus up
  - { key: L, mods: Command, chars: "\x02\x1b\x5b\x43" }  # move focus down
  # windows
  - { key: T, mods: Command,       chars: "\x02\x63" }    # new window
  - { key: T, mods: Command|Shift, chars: "\x02\x40" }    # new window at pwd
  - { key: R, mods: Command,       chars: "\x02\x2c" }    # rename window
  - { key: W, mods: Command|Shift, chars: "\x02\x26" }    # close window
  - { key: N, mods: Command,       chars: "\x02\x6e" }    # next window
  - { key: P, mods: Command,       chars: "\x02\x70" }    # previous window
  # switch to window
  - { key: Key1, mods: Command, chars: "\x02\x31" }
  - { key: Key2, mods: Command, chars: "\x02\x32" }
  - { key: Key3, mods: Command, chars: "\x02\x33" }
  - { key: Key4, mods: Command, chars: "\x02\x34" }
  - { key: Key5, mods: Command, chars: "\x02\x35" }
  - { key: Key6, mods: Command, chars: "\x02\x36" }
  - { key: Key7, mods: Command, chars: "\x02\x37" }
  - { key: Key8, mods: Command, chars: "\x02\x38" }
  - { key: Key9, mods: Command, chars: "\x02\x39" }
  # sessions
  - { key: O, mods: Command,       chars: "\x02\x77" }    # display sessions
  - { key: N, mods: Command|Shift, chars: "\x02\x29" }    # next session
  - { key: P, mods: Command|Shift, chars: "\x02\x28" }    # previous session
  - { key: G, mods: Command,       chars: "\x02\x23" }    # set wd of session to pwd
  - { key: R, mods: Command|Shift, chars: "\x02\x24" }    # rename session
  # popup window
  - { key: E, mods: Command, chars: "\x02\x6a" }          # toggle popup window
  # tmux command line
  - { key: Semicolon, mods: Command, chars: "\x02\x3a" }  # open tmux command line
  # switch themes
  - { key: U, mods: Command|Shift, chars: "\x02\x1b\x4f\x50" }
  - { key: I, mods: Command|Shift, chars: "\x02\x1b\x4f\x51" }
