theme = "catppuccin_mocha"

[editor]
line-number = "relative"
shell = ["zsh", "-c"]
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "block"

[editor.statusline]
left = ["mode", "spacer", "spinner", "diagnostics"]
center = ["file-name"]
right = ["selections"]

