theme = 'rose_pine_moon'

[editor]
line-number = "relative"
shell = ["zsh", "-c"]
cursorline = true
color-modes = true
idle-timeout = 100
soft-wrap.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "block"

[editor.statusline]
left = ["mode", "spacer", "spinner", "diagnostics"]
center = ["version-control", "file-name", "file-modification-indicator"]
right = ["selections", "spacer", "position-percentage"]

[editor.lsp]
display-messages = true
